
platform :ios, '11.0'

def pods
    pod 'SimpleUserDefaults', :path => '../'
end

target 'SimpleUserDefaults_Example' do
    pods
end

target 'SimpleUserDefaults_ExampleTests' do
    pods
end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
